[project]
name = "knucklebones"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "maturin>=1.10.2",
    "numpy>=2.4.0",
    "pygame>=2.5.0",
]
